### ISSUE TITLE
Suggestion: dashboard paged view

### ISSUE THREAD

**Issue by Jurryaany** [krisives/cronnit.us#21]
The dashboard can get slow, sluggish and unresponsive when it has to load many items. Perhaps dividing the list into pages of X amount of posts per page would improve performance on both client and server side.

**Comment by MLanghof** [comment]
I discussed the approach with Kris, quoting him here:

> Pagination should be pretty easy. In dashboard.php get a page number from the user:
> 
>     $pageNumber = intval(@$_GET['page']);
> 
> I would avoid using the variable name "$page", since it may have been used in the scope that is doing the include "$page.php"; in Cronnit.php.
> 
> Then the SQL that is needed is something like:
> 
>     SELECT * FROM blah LIMIT $offset, $pageSize
> 
> In a perfect world that last part would become "LIMIT ?, ?" or similar, but AFAIK MySQL (for whatever reason) doesn't allow those parts of the query to be prepared statement variables, but just make sure they are ints:
> 
>     $pageSize = 50;
>     $offset = $pageNumber * $pageSize;
> 
> Rendering the Pagination HTML tabs is more or less an exercise in Twig:
> 
> 
> ```
> <ol class="pagination">
> {% for i in range(0, pageCount) %}
>    <li {{ i == activePage ? 'class="active"' : '' }}>
>       <a href="/dashboard?page={{ i }}">{{ i }}</a>
>    </li>
> {% endfor %}
> </ol>
> ```
>  
> Or something kind of close to that.

I think 50 would be a reasonable page size, but not 100% sure if we want to really do 1 button per page (the highest post count cronnit user is currently at 4.5k)...

@mstr3336, if you want I'd be glad to have you take a stab at it!

**Comment by mstr3336** [comment]
> not 100% sure if we want to really do 1 button per page

I'm taking this to mean, as in, if a user has 2000 posts, with 50 per page, we shouldn't give them a row of 40 buttons? 
I definitely agree, I feel like 5 either side of current, or something in that ballpark will feel good.

**Comment by MLanghof** [comment]
Yeah, that's what I wanted to express. Not sure if we need "next" and "previous" buttons, but I'm fairly certain we want "first" and "last" buttons.

Some basic sanitization of the `?page=x` input is probably also useful (i.e. clamp to 0 and possibly to `ceil(postCount/50)`).

Finally, I don't really know how we would do pagination on the post-body view. I mean, you could just look at 50 posts at a time but it kinda defeats the purpose of the view if you don't actually see all posts with the same content. If you have a clever idea there I'm very interested to hear it :)

**Comment by mstr3336** [comment]
It'll be very straightforward for chonologically organized posts, but I'm a bit concerned about content-view, since we don't really store the results of hashing and sorting our posts anywhere, so for a user with N posts we'd have to hash and reindex N posts for each page, with an overall load of O(N*N/50) -> O(N^2) for users that navigate from page 1 -> page N/50. 

I'll avoid getting too ahead of myself, the scenario of a user clicking on each and every one of their pages is fairly unlikely, but a more optimal solution that reuses that computation might be warranted downstream.

**Comment by mstr3336** [comment]
> Finally, I don't really know how we would do pagination on the post-body view. I mean, you could just look at 50 posts at a time but it kinda defeats the purpose of the view if you don't actually see all posts with the same content. 

We arrived at pretty much the same conclusion 

A few things of note about the body view is that it necessarily has to render a lesser or equal amount of thumbnails than post-view, and I'd bet almost anything that your most prolific users (Eg. user w/ 4.5k posts) likely have a large degree of duplication in their post bodies across a wide range of subs - meaning that the actual instance thumbnails being rendered are fairly few- 

My own posting pattern, just counting those submitted via cronnit, typically appears to hit around 3-6 subs per instance, sometimes a fair bit more. 

Potential approaches/workarounds

* Offer an "escape hatch"/view option to disable thumbnails - instead of showing gifs, embeds, just give them a link as with the "link" thumbnail block. Can just put a toggle in the nav bar, or something.
* This sonds kinda kludgey, but I'll still throw it out there - When templating, chuck in a `<script>` div id'd `"data-for-post-view"` which contains a json dump of `$indexedPosts`.  
  * :heavy_check_mark:  This is no more expensive server-side than a full render of every post, and also necessarily less expensive client-side than a full render of every post
  * :thought_balloon: This is something that I often see in `R` `htmlwidget` applications - I'll find an example.
  * :x: Pagination would take place client-side, and javascript/jQuery can do the bulk of the  work in preparing the DOM. 
   * :x: I kind of hate javascript and this would add a tonne of complexity- 
   * :x: We'd need an entirely new templating system for the front-end
   * I think I dont like this idea

**Comment by MLanghof** [comment]
> A few things of note about the body view is that it necessarily has to render a lesser or equal amount of thumbnails than post-view

...which need not mean that it is significantly less resource-intensive. Your browser won't re-download the same image twice (not sure about iframes) and I'd also expect that it reuses the assets (so memory won't go up much from using an image multiple times).

> and I'd bet almost anything that your most prolific users (Eg. user w/ 4.5k posts) likely have a large degree of duplication in their post bodies across a wide range of subs - meaning that the actual instance thumbnails being rendered are fairly few

I thought so too but that's not necessarily the case. According to the database, we have several users with over a thousand uniquely-bodied posts. Of course there are also users with only one unique post body posted over and over, so it spans pretty much the entire range.

> Offer an "escape hatch"/view option to disable thumbnails - instead of showing gifs, embeds, just give them a link as with the "link" thumbnail block. Can just put a toggle in the nav bar, or something.

Yeah, that's more or less an easy way out. Still, you'd want to persist it somehow (so that you don't have to change the option every time) but then what happens when the user enables thumbnails and can no longer load the dashboard? Tricky. We'll have to find a different solution either way.

> [client-side pagination]

I agree with your sentiment. Meh.

---

I'm currently investigating whether it's possible to write a decent query for this problem.

According to my tests, the following is reasonably fast (~10 ms):

   SELECT min(id) AS p_id, body FROM post WHERE account_id = xyz GROUP BY body

It selects the lowest post ID for each unique body of that account. However, without an index on `body` (would that be reasonable?) it still has to sort all the rows in some temporary storage, which has caused surprising issues in the past (we had to add [this](https://github.com/krisives/cronnit.us/commit/ca1cf54e04e49bf618fd60beed7e9592d6f87ab7#diff-fbab1347e24a3eae10b995632137be91R59) combined index to have the main query we run not do external sorting).

I'll see if I can get Kris to weigh in.

**Comment by MLanghof** [comment]
In either case, I think it's a good idea to get pagination for the default list view off the ground.

**Comment by mstr3336** [comment]
>  However, without an index on body (would that be reasonable?) 

I'm by no means an SQL expert, but I think an index on `hash(body)` (pseudocode) sounds more than reasonable to me, assuming that DBs may index on strings (If not, it seems straightforward to make `hash` return raw binary, and to cast that to `int`).

Ensuring that the hash is updated when posts are submitted, edited, and so on is important, it might be worth wrapping that behaviour in a method, and I'm unsure of the logistics of applying this hashing to all previously submitted posts bodies.

**Comment by mstr3336** [comment]
I think writing a query with `group by` sounds like the cleanest approach - It's how I'd approach a similar pattern when programming data transformation using `R`'s `dplyr`, which allows for similar patterns to SQL queries, but with a very different interface.

**Comment by MLanghof** [comment]
So the problem with writing a query to group by body is that it will also just be O(N²) in the same way without an index, and you can't have an index in MySQL on (arbitrary sized) text columns. A workaround would be to hash the body, store the hash and index that. Which is kinda awkward.

Kris said we should probably just keep doing it the way we do it right now and group the content server-side and then paginate afterwards. Yeah, it's theoretically O(N²), but it's not really something to worry about in practice (how many people will really go through a large number of pages on a regular basis?). I mean, it's no worse than what we do at the moment and we can always improve it later.

**Comment by mstr3336** [comment]
>  Yeah, it's theoretically O(N²), but it's not really something to worry about in practice (how many people will really go through a large number of pages on a regular basis?).

Completely agree, also, i don't know how cronnit is hosting, but mosy 0..N traversals undertook by users are going to take place over like... 3 minutes i guess? Unless they're acting in bad faith in which case they probably need to be rate limited anyway (I don't think we have a lot of rate limiting between cronnit and client established yet)
But it'll probably track at this point.

I'm not sure when I'll work on cronnit next, I like working on it, but it definitely takes time, and my actual job pays me, so I'm not sure whether you or I will be first to the punch to implement pagination, but for now, implementing it across list view should be fine

**Comment by mstr3336** [comment]
Another take from [this SO thread](https://stackoverflow.com/questions/11757016/performance-differences-between-visibilityhidden-and-displaynone):

 https://stackoverflow.com/a/11757103/9238801

>  `display:none;` elements are [not in the render tree all](http://www.html5rocks.com/en/tutorials/internals/howbrowserswork/#Render_tree_construction), so they will perform better at face value.
> 
> I doubt you will have any real visible performance problems from this though. If you  need `opacity: 0` or `visibility: hidden` **because of their functionality**, then just use them. If you don't need the functionality, then use `display: none;`

Perhaps breaking up each "page" into a div, letting users select the page on the front-end & toggling the `display` attribute could be a good-enough approach that services both views, content & list. 

Here's a fiddle, with a snapshot of my own cronnit, and a few tweaks in the DOM, just using the first client-side pagination library I found: https://jsfiddle.net/matthewstrasiotto/d0gakvz6/

**Comment by mstr3336** [comment]
Apparently native lazy loading doesn't really apply to iFrames that have `display: none;` set, so maybe this implementation isn't going to cut it. 

https://web.dev/native-lazy-loading/#is-lazy-loading-for-iframes-also-supported-in-chrome

> The loading attribute affects iframes differently than images, depending on whether the iframe is hidden. (Hidden iframes are often used for analytics or communication purposes.) Chrome uses the following criteria to determine whether an iframe is hidden:

> 
> The iframe's width and height are 4 px or smaller.
> display: none or visibility: hidden is applied.
> The iframe is placed off-screen using negative X or Y positioning.
> If an iframe meets any of these conditions, Chrome considers it hidden and won't lazy-load it in most cases.

The https://github.com/aFarkas/lazysizes js library provides a fairly robust, clean, and understandable implementation / API for lazy loading that seems to reliably lazy-load iframes, and that could be useful in general, though cramming a bunch of random javascript libraries into the project is probably jumping the gun somewhat

**Comment by mstr3336** [comment]
https://github.com/aFarkas/lazysizes/issues/570

**Comment by mstr3336** [comment]
Of relevance to DB backed pagination (content view):
https://dba.stackexchange.com/questions/240999/indexing-a-sha-hash-in-place-of-a-varchar
https://dev.mysql.com/doc/refman/5.6/en/index-btree-hash.html

(I'll be circling back  to these)

**Comment by mstr3336** [comment]
https://dev.mysql.com/doc/refman/5.7/en/alter-table-generated-columns.html

**Comment by mstr3336** [comment]
https://dev.mysql.com/doc/refman/5.7/en/encryption-functions.html

**Comment by mstr3336** [comment]
> Applying it [a generated column that is a hash of the body column] to all existing posts wouldn't be too bad but keeping it up-to-date is the kind of thing that just attracts bugs like a campfire at night.

I think that a MySQL generated column feature may mitigate this (very reasonable, if this were otherwise done at the php layer) concern, and if it's feasible, probably addresses all of our reservations about efficient DB backed server-side pagination.

**Comment by mstr3336** [comment]
The following effectively accomplished this (Performed interactively): 

```mysql
ALTER TABLE `post` ADD `hash` BINARY(16) GENERATED ALWAYS AS (UNHEX(MD5(body))) STORED;
```

However, RedBeanPhp will throw an error when you attempt to update:
```
Undefined index: nsfw in /home/cronnit/pages/edit.php on line 41
[Thu Sep  3 06:00:15 2020] PHP Notice:  [HY000] - SQLSTATE[HY000]: General error: 1906 The value specified for generated column 'hash' in table 'post' has been ignored
trace: #0 /home/cronnit/vendor/gabordemooij/redbean/RedBeanPHP/Driver/RPDO.php(546): RedBeanPHP\Driver\RPDO->runQuery()
#1 /home/cronnit/vendor/gabordemooij/redbean/RedBeanPHP/Adapter/DBAdapter.php(107): RedBeanPHP\Driver\RPDO->Execute()
#2 /home/cronnit/vendor/gabordemooij/redbean/RedBeanPHP/QueryWriter/AQueryWriter.php(901): RedBeanPHP\Adapter\DBAdapter->exec()
#3 /home/cronnit/vendor/gabordemooij/redbean/RedBeanPHP/Repository/Fluid.php(227): RedBeanPHP\QueryWriter\AQueryWriter->updateRecord()
#4 /home/cronnit/vendor/gabordemooij/redbean/RedBeanPHP/Repository.php(121): RedBeanPHP\Repository\Fluid->storeBean()
#5 /home/cronnit/vendor/gabordemooij/redbean/RedBeanPHP/Repository.php(516): RedBeanPHP\Repository->storeBeanWithLists()
#6 /home/cronnit/vendor/gabordemooij/redbean/RedBeanPHP/OODB.php(388): RedBeanPHP\Repository->store()
#7 /home/cronnit/vendor/gabordemooij/redbean/RedBeanPH in /home/cronnit/Cronnit.php on line 91
```

The reason behind this is that under the default behaviour, when you call `R::store()` using RedBeanPHP, RedBeanPHP will attempt to update the entire bean. 

[https://redbeanphp.com/api/classes/RedBeanPHP.Facade.html#method_usePartialBeans](toggling usePartialBeans) should address this:

> *Toggles 'partial bean mode'. If this mode has been selected the repository will only update the fields of a bean that have been changed rather than the entire bean.*

> Pass the value TRUE to select 'partial mode' for all beans. Pass the value FALSE to disable 'partial mode'. Pass an array of bean types if you wish to use partial mode only for some types. This method will return the previous value.

A similar use case for partial beans is documented here: (using MySQL `TRIGGER`s, rather than generated columns, but these two things are very similar)

https://github.com/gabordemooij/redbean/issues/579

**Comment by MLanghof** [comment]
Just wanted to say that I deeply appreciate your investigations here. Work is really busy for me right now so I can't spend time on cronnit atm, but maybe Sunday will allow for something.

**Comment by MLanghof** [comment]
Generated columns seem exactly like the thing we need here, very cool! I have zero experience with them, so I'll page Kris to see if he has any reservations (beyond interfering with Redbean :D).

Since it's not been linked yet (the "mentioned by" graph of this repo sure has to look funky at this point), I'll mention that you implemented this in #53.

**Comment by matthewstrasiotto** [comment]
> Generated columns seem exactly like the thing we need here, very cool! I have zero experience with them, so I'll page Kris to see if he has any reservations (beyond interfering with Redbean :D).

They mainly just work, from what I've seen, which is nice.
The caveats are that you have to enable partial beans, so that RB doesnt try to write back to them, 

and (less to do with generated cols and more to do with hashed cols) storing an MD5 digest col as BINARY(16) rather than CHAR(32) does NOT work with RB, 

CHAR(32) encoding is needed, otherwise RB seems to be unable to actually pull the beans via ownlists into PHP objects, and fails silently (returns an empty list FWIR)

Worth raising an issue in RBPHP, maybe, because I think throwing an error or warning is in order
